server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:scheduling-service}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/Foodopia_scheduling}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

logging:
  level:
    com:
      foodopia:
        scheduling: DEBUG
    org:
      springframework:
        data:
          mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

info:
  app:
    name: ${spring.application.name}
    description: "Foodopia Scheduling Service"
    version: "0.0.1-SNAPSHOT"
