version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: foodopia-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - foodopia-network

  # Authentication Service
  auth-service:
    image: ${AUTH_IMAGE:-whz0000727/foodopia-auth:latest}
    container_name: foodopia-auth-service
    environment:
      # MongoDB Configuration
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_APP_NAME: ${MONGODB_APP_NAME}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800000}
    depends_on:
      - mongodb
    networks:
      - foodopia-network
    ports:
      - "8081:8081"

volumes:
  mongodb_data:

networks:
  foodopia-network:
    driver: bridge