# Eureka Server Configuration
server:
  port: 8070

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:eurekaserver}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

# Eureka Server Configuration
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    # Don't register the Eureka server with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

# Logging Configuration
logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application Info
info:
  app:
    name: ${spring.application.name}
    description: "Foodopia Eureka Discovery Server"
    version: "1.0.0"