server:
    port: 9010

spring:
  application:
    name: "notification"

  cloud:
    function:
      definition: sendEmail|sendSms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}

      kafka:
        binder:
          brokers:
            - localhost:9092