server:
  port: 9020

spring:
  application:
    name: "notification"
  cloud:
    function:
      definition: authEmail|authSms
    stream:
      bindings:
        authEmailauthSms-in-0:
          destination: foodopia-auth-events
          group: ${spring.application.name}
        authEmailauthSms-out-0:
          destination: auth-notification-sent
      kafka:
        binder:
          brokers:
            - localhost:9092

logging:
  level:
    com:
      foodopia:
        notification: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"